name: CI with Datree's policy check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://get.datree.io | /bin/bash
    - run: datree test ~/.datree/k8s-demo.yaml
