name: GitHub Actions Workshop

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Get a random gif
        env:
          TAG: "hello"
        id: random_gif
        run: |
          echo ::set-output name=get_url::$(curl https://api.giphy.com/v1/gifs/random?api_key=0UTRbFtkMxAplrohufYco5IY74U8hOes&tags=$TAG)
          
      - name: Add a comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: "fail"
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "![GIF](${{fromJson(steps.random_gif.outputs.get_url).data.image_url}})" }'
