name: GitHub Actions Workshop

on: pull_request
# on:
#   schedule:
#     - cron:  '*/10 * * * *'
    
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Get a random gif
        env:
          TAG: "goat"
        id: random_gif
        run: |
          echo ::set-output name=get_url::$(curl https://api.giphy.com/v1/gifs/random?api_key=0UTRbFtkMxAplrohufYco5IY74U8hOes&tag=$TAG)
      
      - uses: actions/checkout@v2
          
      - name: Create new issue
        uses: imjohnbo/issue-bot@v3
        with:
          title: Hello, world
          body: |
            Here is a randome GIF:<br/>![GIF](${{fromJson(steps.random_gif.outputs.get_url).data.image_url}})
          pinned: true

#       - name: Add a comment to PR
#         env:
#           URL: ${{ github.event.pull_request.comments_url }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           curl \
#             -X POST \
#             $URL \
#             -H "Content-Type: application/json" \
#             -H "Authorization: token $GITHUB_TOKEN" \
#             --data '{ "body": "Here is a randome GIF:<br/>![GIF](${{fromJson(steps.random_gif.outputs.get_url).data.image_url}})" }'
