name: GitHub Actions Workshop

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add comment to PR
        if: contains(github.event.comment.body, 'special string')
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'
